### ISSUE TITLE
Reduce TOC level

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-2020-work-programme#5]
Hey @MattBlissett—

I'm apparently not smart enough to follow seemingly simple instructions aimed at reducing the number of headers included in the lefthand-nav table of contents in our electronic document here:
https://docs.gbif-uat.org/2020-work-programme/

I would've thought it was just changing the number in line 3 [here](https://github.com/gbif/doc-2020-work-programme/blob/master/index.en.adoc), but it doesn't seem to have any effect.

I think we dropping one level from the current display would make the TOC much more manageable, especially knowing that any and all headers of any level have discrete links that we can use if needed. That means that, reading from the top, [Financial situation](https://docs.gbif-uat.org/2020-work-programme/en/#_financial_situation) would remain in the list, but [Priority area 1](https://docs.gbif-uat.org/2020-work-programme/en/#_priority_area_1) would drop out, leaving [Areas to expand activity](https://docs.gbif-uat.org/2020-work-programme/en/#_areas_to_expand_activity) to come next.

Hope this makes sense. Really frustrated that I'm not self-service on this one.

**Comment by MattBlissett** [comment]
It was fixed by the build script; I've removed that.

The default (if nothing is specified) is 2.
